main: yy.gourlitburo.yeyaknife.Main
name: YeyaKnife
version: 0.0.4
api-version: 1.15
author: Zack Guard
description: A command line interface to the Spigot API.
commands:
  yeyaknife:
    aliases: [yk]
    description: Use YeyaKnife.
    usage: "Usage: /yk <cmd> <subcmd> [<args>]"
    permission: yeyaknife.use
permissions:
  yeyaknife.use:
    default: op
